### ISSUE TITLE
PresenceLight Stops Updating

### ISSUE THREAD

**Issue by gizmohd** [isaacrlevin/presencelight#245]
**Describe the bug**
After an undetermined amount of time the presencelight application  fails to update activitiy or availability status.  And the only known fix is to close the application and restart.

May have a top

**To Reproduce**
1.  Application Runs in background on machine a
2. Teams status and/activity is updated on machine b

**Expected behavior**
Eventually application stops retrieving updates for Teams activities and availability

**Screenshots**

## Further details
- OS:  Windows 10
- PresenceLight App Type Desktop
- PresenceLight Version: 3.5.15.0
- Did you clear settings.json? Yes

**Comment by isaacrlevin** [comment]
Do you have any idea how long the app is running for?

**Comment by isaacrlevin** [comment]
Also, you are on a super old version. You should update the app to the store

**Comment by gizmohd** [comment]
Strange.. I literally just installed it from the app store yesterday...

**Comment by gizmohd** [comment]
[image: image.png]

**Comment by gizmohd** [comment]
As for how long... it times out just after an hour.

**Comment by isaacrlevin** [comment]
See If you have the same experience with the newest version of the app

**Comment by gizmohd** [comment]
3.5.15.0 is the newest version available on the App Store..

**Comment by isaacrlevin** [comment]
I just confirm that, that is weird. I just pushed a new version to the store should be available the next day or so

**Comment by fabian-we** [comment]
I can confirm the issue, and it seems to also happen on version  3.7.28.
Are there any log files that could help?

**Comment by cakeinmilk** [comment]
Just adding that I also have this same issue

**Comment by sborg-ms** [comment]
+1 on 3.7.28  no longer working in changing / setting lifx light to match teams status...

**Comment by gizmohd** [comment]
may want to consider adding some debug logging (Serilog?) to allow
localized Verbose logging to help in the troubleshooting....  It almost
feels like it's not updating/getting the refresh token and the Azure auth
is timing out...   Something is.. but without any exception logs it makes
it hard to help troubleshoot with/for ya.. :)

**Comment by fabian-we** [comment]
I think I found something!
I've cloned the repo and run the code directly and at some point I got an exception at this line in the `GetPresence()` method:

`return await _graphServiceClient.Me.Presence.Request().GetAsync().ConfigureAwait(true);`

Unfortunately I was too quick to step through the code, so I didn't save the exact exception message, but it was some sort of network error.

I think the exception cancels the loop in `InteractWithLights()` and therefore stops all further updates to the status.
Perhaps it would be enough to move the try/catch inside the loop?

**Comment by isaacrlevin** [comment]
There were two things occuring related to me making a change for Working Hours. This is now fixed in Nightly.

On a side note, there are logs available at.

C:\Users\user\AppData\Local\PresenceLight\logs

I also send telemetry to application insights as well.

**Comment by sborg-ms** [comment]
new nightly install fails with :

App installation failed with error message: Deployment Add operation with target volume C: on Package 37828IsaacLevin.197278F15330A.Nightly_3.7.30.0_neutral_~_jvewcxq8vj8qt from:  (PresenceLight.Package_3.7.30.0_x64.appxbundle)  failed with error 0x80190193. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80190193)

**Comment by isaacrlevin** [comment]
@sborg-ms restart machine? It installed for me just now fine. I also didn't have an existing verision

**Comment by sborg-ms** [comment]
@isaacrlevin  - restarted a few times now - just either hangs on install or gives that error... Trying to avoid uninstall and full re-setup!

**Comment by isaacrlevin** [comment]
You could just copy the Json file and re-add it after reinstalling

**Comment by sborg-ms** [comment]
@isaacrlevin  interesting now i cannot even Uninstall via programs .. Just fails to uninstall...

**Comment by sborg-ms** [comment]
ok -  that was super painful - many reboots, and retrying and finally got it uninstalled and re-installed. v3.7.30.0

The teams syncing with my Lifx is still not working at all.

**Comment by sborg-ms** [comment]
> 
> C:\Users\user\AppData\Local\PresenceLight\logs
> 
Found in C:\Users\<user>\AppData\Local\Packages\37828IsaacLevin.197278F15330A.Nightly_jvewcxq8vj8qt\LocalCache\Local\PresenceLight\logs

and seeing the following but no light interaction/changes

2021-02-04 15:12:56.2527|Info|PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 790 | 
2021-02-04 15:12:56.7611|Info|Setting LIFX Light id:d073d540948e to FFFF00 - LifxService:SetColor Line: 257 | 
2021-02-04 15:13:02.5871|Info|PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 790 | 
2021-02-04 15:13:02.9675|Info|Setting LIFX Light id:d073d540948e to FFFF00 - LifxService:SetColor Line: 257 | 
2021-02-04 15:13:09.0413|Info|PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 790 | 
2021-02-04 15:13:09.5146|Info|Setting LIFX Light id:d073d540948e to FFFF00 - LifxService:SetColor Line: 257 | 
2021-02-04 15:13:15.3539|Info|PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 790 | 
2021-02-04 15:13:15.7363|Info|Setting LIFX Light id:d073d540948e to FFFF00 - LifxService:SetColor Line: 257 |

**Comment by isaacrlevin** [comment]
> > C:\Users\user\AppData\Local\PresenceLight\logs
> 
> Found in C:\Users<user>\AppData\Local\Packages\37828IsaacLevin.197278F15330A.Nightly_jvewcxq8vj8qt\LocalCache\Local\PresenceLight\logs
> 
> and seeing the following but no light interaction/changes
> 
> 2021-02-04 15:12:56.2527|Info|PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 790 |
> 2021-02-04 15:12:56.7611|Info|Setting LIFX Light id:d073d540948e to FFFF00 - LifxService:SetColor Line: 257 |
> 2021-02-04 15:13:02.5871|Info|PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 790 |
> 2021-02-04 15:13:02.9675|Info|Setting LIFX Light id:d073d540948e to FFFF00 - LifxService:SetColor Line: 257 |
> 2021-02-04 15:13:09.0413|Info|PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 790 |
> 2021-02-04 15:13:09.5146|Info|Setting LIFX Light id:d073d540948e to FFFF00 - LifxService:SetColor Line: 257 |
> 2021-02-04 15:13:15.3539|Info|PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 790 |
> 2021-02-04 15:13:15.7363|Info|Setting LIFX Light id:d073d540948e to FFFF00 - LifxService:SetColor Line: 257 |

Get a new token

**Comment by sborg-ms** [comment]
:) - I did !  and even went and reset the lifx light and added it back in from scratch!... Lifx app can control light etc ok.  refreshed in presence and selected the light again and still no luck!

**Comment by isaacrlevin** [comment]
Can you start fiddler before Pl and see what the response from the lifx call is?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by fabian-we** [comment]
I think the issue from @sborg-ms  is a different issue than @gizmohd and mine?
Anyway - I continued digging a bit deeper. First of: I had the windows store version installed and the newest version available from the GitHub releases and neither did write the log file (what's up with that?). The version I compiled myself DID write the logs. Unfortunately the logging of exceptions doesn't really work, and all I got in the log is this:

> 2021-02-04 09:09:48.5998|Error|Error Occured - MainWindow.xaml:GetPresence Line: 504 | 
> 2021-02-04 09:10:10.5899|Error|Error Occured - MainWindow.xaml:InteractWithLights Line: 847 | 

Not really helpful. Not sure what the issue is, as the NLog configuration looks correct to me.

I just appended the exception to the log message text manually, and here we go:

>System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
> ---> System.TimeoutException: The operation was canceled.
> ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
> ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
> ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
>   --- End of inner exception stack trace ---
>   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
>   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
>   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   --- End of inner exception stack trace ---
>   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at Microsoft.Graph.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at Microsoft.Graph.RetryHandler.SendAsync(HttpRequestMessage httpRequest, CancellationToken cancellationToken)
>   at Microsoft.Graph.CompressionHandler.SendAsync(HttpRequestMessage httpRequest, CancellationToken cancellationToken)
>   at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
>   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
>   --- End of inner exception stack trace ---
>   --- End of inner exception stack trace ---
>   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
>   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
>   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
>   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
>   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
>   at Microsoft.Graph.PresenceRequest.GetAsync(CancellationToken cancellationToken)
>   at PresenceLight.MainWindow.GetPresence() in C:\dev\presencelight\src\DesktopClient\PresenceLight\MainWindow.xaml.cs:line 500
>   at PresenceLight.MainWindow.InteractWithLights() in C:\dev\presencelight\src\DesktopClient\PresenceLight\MainWindow.xaml.cs:line 791

And after that the polling loop is broken!

Like I proposed in my previous comment, I've moved the try/catch inside the loop and so far this looks promising. I've already seen the exception in the log again, but the loop continues and the status keeps getting updated. This looks like a viable solution to me.
By the way, another easy way to trigger this bug is to create a firewall rule and block outgoing PresenceLight traffic. The exception is different but it causes the same issue.

I'll try to prepare a pull request, but probably don't have time before the weekend.

**Comment by mattjrobertsCDW** [comment]
I am having the same issue, after a couple of hours of switching status it seems to stop syncing, I have tried removing the app and reinstalling but the version currently coming from the UK MS store is 3.5.15.0 - somewhat out of date - hoping for an update to the store soon as I love this when it is syncing!

**Comment by isaacrlevin** [comment]
I have seen this graph timeout before (just as a heads up, I am looking to implement retry logic for this issue). I welcome your PR however!!!

**Comment by isaacrlevin** [comment]
> I think the issue from @sborg-ms is a different issue than @gizmohd and mine?
> Anyway - I continued digging a bit deeper. First of: I had the windows store version installed and the newest version available from the GitHub releases and neither did write the log file (what's up with that?). The version I compiled myself DID write the logs. Unfortunately the logging of exceptions doesn't really work, and all I got in the log is this:
> 
> > 2021-02-04 09:09:48.5998|Error|Error Occured - MainWindow.xaml:GetPresence Line: 504 |
> > 2021-02-04 09:10:10.5899|Error|Error Occured - MainWindow.xaml:InteractWithLights Line: 847 |
> 
> Not really helpful. Not sure what the issue is, as the NLog configuration looks correct to me.
> 
> I just appended the exception to the log message text manually, and here we go:
> 
> > System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
> > ---> System.TimeoutException: The operation was canceled.
> > ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
> > ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
> > ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
> > --- End of inner exception stack trace ---
> > at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
> > at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
> > at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
> > at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> > --- End of inner exception stack trace ---
> > at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> > at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
> > at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> > at Microsoft.Graph.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> > at Microsoft.Graph.RetryHandler.SendAsync(HttpRequestMessage httpRequest, CancellationToken cancellationToken)
> > at Microsoft.Graph.CompressionHandler.SendAsync(HttpRequestMessage httpRequest, CancellationToken cancellationToken)
> > at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
> > at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
> > --- End of inner exception stack trace ---
> > --- End of inner exception stack trace ---
> > at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
> > at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
> > at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
> > at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
> > at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
> > at Microsoft.Graph.PresenceRequest.GetAsync(CancellationToken cancellationToken)
> > at PresenceLight.MainWindow.GetPresence() in C:\dev\presencelight\src\DesktopClient\PresenceLight\MainWindow.xaml.cs:line 500
> > at PresenceLight.MainWindow.InteractWithLights() in C:\dev\presencelight\src\DesktopClient\PresenceLight\MainWindow.xaml.cs:line 791
> 
> And after that the polling loop is broken!
> 
> Like I proposed in my previous comment, I've moved the try/catch inside the loop and so far this looks promising. I've already seen the exception in the log again, but the loop continues and the status keeps getting updated. This looks like a viable solution to me.
> By the way, another easy way to trigger this bug is to create a firewall rule and block outgoing PresenceLight traffic. The exception is different but it causes the same issue.
> 
> I'll try to prepare a pull request, but probably don't have time before the weekend.

I have seen this graph timeout before (just as a heads up, I am looking to implement retry logic for this issue). I welcome your PR however!!!

**Comment by isaacrlevin** [comment]
@sborg-ms your issue should now be fixed and I added Polly retry to the graph call. Let's see how that makes things. Newest Nightly

![image](https://user-images.githubusercontent.com/8878502/106950819-cf82d780-66e3-11eb-8a1e-82c95cbdbc48.png)

**Comment by sborg-ms** [comment]
@isaacrlevin  - new version 3.7.34.0 (finally) installed [manually uninstalled nightly and current release].

Now successfully sync teams status to Lifx again.

**Comment by isaacrlevin** [comment]
@gizmohd @fabian-we can you confirm latest nightly resolves your issue so I can close this issue ;)

**Comment by cazador481** [comment]
I am running 3.7.36.0 , and I am still having issues with it picking up a change in my status.
[presencelight.log](https://github.com/isaacrlevin/presencelight/files/5936235/presencelight.log)

**Comment by isaacrlevin** [comment]
@cazador481 do you have an all. Log

**Comment by cazador481** [comment]
Not that I can find.

**Comment by fabian-we** [comment]
I tried the nightly version, and the issue seems to be resolved 👍 
It's weekend so I can't say how it would hold up at a normal work day, but at least it now keeps working if I temporarily block PresenceLight with the Windows firewall.

Thank you very much for the quick fix!

**Comment by gizmohd** [comment]
I've migrated over to using the Blazor/Containerized platform since it makes more sense in my home environment... I have submitted a PR to the repo to better support K8s/Docker in multiple environments and some enhanced logging.

**Comment by isaacrlevin** [comment]
@cazador481 that is a pretty bare log file. What is your configuration like? You can email your appsettings file to isaac@isaaclevin.com and I can take a look

**Comment by isaacrlevin** [comment]
@cazador481 a fix for this is in the newest nightly 3.7.37

**Comment by cazador481** [comment]
Still not working, and the log files are empty as ever.

**Comment by isaacrlevin** [comment]
@cazador481 please open the new issue. 

Since I don't have a custom API, the way that I test this is by looking in Fiddler and seeing if the requests are being made 

In the new issue please add screenshot in fiddler while the app is running
